// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_GRAPH_ALIGN_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_GRAPH_ALIGN_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// AlignConfig

template <bool TTop , bool TLeft , bool TRight , bool TBottom , typename TSpec > class AlignConfig;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(66)

//____________________________________________________________________________
// AlignTraceback

template <typename TSize> struct AlignTraceback;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(96)

//____________________________________________________________________________
// TraceBack_

struct TraceBack_;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(85)

//____________________________________________________________________________
// TranslateTableByteToTraceback_

template <typename T > struct TranslateTableByteToTraceback_;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(47)

} //namespace SEQAN_NAMESPACE_MAIN


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// TraceBack

typedef SimpleType<unsigned char, TraceBack_> TraceBack;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(86)

} //namespace SEQAN_NAMESPACE_MAIN


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// _alignBandedGotoh

template <typename TTrace, typename TStringSet, typename TScore, typename TValPair, typename TIndexPair, typename TDiagonal, typename TAlignConfig> inline typename Value<TScore>::Type _alignBandedGotoh(TTrace& trace, TStringSet const& str, TScore const & sc, TValPair& overallMaxValue, TIndexPair& overallMaxIndex, TDiagonal diagL, TDiagonal diagU, TAlignConfig const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_gotoh.h"(158)

//____________________________________________________________________________
// _alignBandedGotohTrace

template <typename TAlign, typename TStringSet, typename TTrace, typename TValPair, typename TIndexPair, typename TDiagonal> inline void _alignBandedGotohTrace(TAlign& align, TStringSet const& str, TTrace const& trace, TValPair const& overallMaxValue, TIndexPair const& overallMaxIndex, TDiagonal const diagL, TDiagonal const diagU);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_gotoh.h"(54)

//____________________________________________________________________________
// _alignBandedNeedlemanWunsch

template <typename TTrace, typename TStringSet, typename TScore, typename TValPair, typename TIndexPair, typename TDiagonal, typename TAlignConfig> inline typename Value<TScore>::Type _alignBandedNeedlemanWunsch(TTrace& trace, TStringSet const& str, TScore const & sc, TValPair& overallMaxValue, TIndexPair& overallMaxIndex, TDiagonal diagL, TDiagonal diagU, TAlignConfig const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(176)
template <typename TTrace, typename TStringSet, typename TScore, typename TValPair, typename TIndexPair, typename TDiagonal, typename TAlignConfig> inline typename Value<TScore>::Type _alignBandedNeedlemanWunsch(TTrace& trace, TStringSet const& str, TScore const & sc, TValPair& overallMaxValue, TIndexPair& overallMaxIndex, TDiagonal diagL, TDiagonal diagU, TAlignConfig const, String<Pair<typename Value<TScore>::Type,int> > & maxCols, unsigned minColNum);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(284)

//____________________________________________________________________________
// _alignBandedNeedlemanWunschTrace

template <typename TAlign, typename TStringSet, typename TTrace, typename TValPair, typename TIndexPair, typename TDiagonal> inline void _alignBandedNeedlemanWunschTrace(TAlign& align, TStringSet const& str, TTrace const& trace, TValPair const& overallMaxValue, TIndexPair const& overallMaxIndex, TDiagonal const diagL, TDiagonal const diagU);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(53)

//____________________________________________________________________________
// _alignBandedSmithWaterman

template <typename TTrace, typename TStringSet, typename TScore, typename TIndexPair, typename TDiagonal, typename TForbidden> inline typename Value<TScore>::Type _alignBandedSmithWaterman(TTrace& trace, TStringSet const& str, TScore const& sc, typename Value<TTrace>::Type& initialDir, TIndexPair& indexPair, TDiagonal diagL, TDiagonal diagU, TForbidden forbidden);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(172)

//____________________________________________________________________________
// _alignBandedSmithWatermanTrace

template <typename TStringSet, typename TAlign, typename TTrace, typename TVal, typename TIndexPair, typename TDiagonal, typename TForbidden> inline void _alignBandedSmithWatermanTrace(TStringSet const& str, TAlign& align, TTrace const& trace, TVal const initialDir, TIndexPair const& indexPair, TDiagonal diagL, TDiagonal diagU, TForbidden& forbidden);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(94)

//____________________________________________________________________________
// _alignGotoh

template <typename TTrace, typename TStringSet, typename TScore, typename TValPair, typename TIndexPair, typename TAlignConfig> inline typename Value<TScore>::Type _alignGotoh(TTrace& trace, TStringSet const& str, TScore const & sc, TValPair& overallMaxValue, TIndexPair& overallMaxIndex, typename Value<TTrace>::Type& initialDir, TAlignConfig const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_gotoh.h"(163)

//____________________________________________________________________________
// _alignGotohTrace

template <typename TAlign, typename TStringSet, typename TTrace, typename TIndexPair, typename TVal> inline void _alignGotohTrace(TAlign& align, TStringSet const& str, TTrace const& trace, TIndexPair const& overallMaxIndex, TVal const initialDir);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_gotoh.h"(52)

//____________________________________________________________________________
// _alignHirschberg

template <typename TTrace, typename TStringSet, typename TScoreValue, typename TSpec> TScoreValue _alignHirschberg(TTrace& trace, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, Hirschberg);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_hirschberg.h"(134)

//____________________________________________________________________________
// _alignHirschbergTrace

template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TTrace> void _alignHirschbergTrace(TAlign& align, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TTrace& trace);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_hirschberg.h"(53)

//____________________________________________________________________________
// _alignNeedlemanWunsch

template <typename TTrace, typename TStringSet, typename TScore, typename TValPair, typename TIndexPair, typename TAlignConfig> inline typename Value<TScore>::Type _alignNeedlemanWunsch(TTrace & trace, TStringSet const & str, TScore const & _sc, TValPair & overallMaxValue, TIndexPair & overallMaxIndex, TAlignConfig const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_needleman_wunsch.h"(144)

//____________________________________________________________________________
// _alignNeedlemanWunschMatrix

template <typename TAlign, typename TStringSet, typename TTrace, typename TIndexPair> inline void _alignNeedlemanWunschMatrix(TAlign&, TStringSet const&, TTrace const&, TIndexPair const&);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_needleman_wunsch.h"(50)

//____________________________________________________________________________
// _alignNeedlemanWunschTrace

template <typename TAlign, typename TStringSet, typename TTrace, typename TIndexPair> void _alignNeedlemanWunschTrace(TAlign& align, TStringSet const& str, TTrace const& trace, TIndexPair const& overallMaxIndex);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_needleman_wunsch.h"(60)

//____________________________________________________________________________
// _alignSmithWaterman

template <typename TTrace, typename TStringSet, typename TScore, typename TIndexPair, typename TForbidden> inline typename Value<TScore>::Type _alignSmithWaterman(TTrace& trace, TStringSet const& str, TScore const & sc, typename Value<TTrace>::Type& initialDir, TIndexPair& indexPair, TForbidden& forbidden);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(214)

//____________________________________________________________________________
// _alignSmithWatermanTrace

template <typename TAlign, typename TStringSet, typename TTrace, typename TVal, typename TIndexPair, typename TForbidden> inline void _alignSmithWatermanTrace(TAlign& align, TStringSet const& str, TTrace const& trace, TVal const initialDir, TIndexPair const& indexPair, TForbidden& forbidden);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(104)

//____________________________________________________________________________
// _alignTracePrint

template <typename TFile, typename TStringSet, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(TFile& file, TStringSet const& str, TId const , TPos const pos1, TId const , TPos const pos2, TPos const segLen, TTraceValue const tv);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(117)
template <typename TStringSet, typename TCargo, typename TSpec, typename TStringSet2, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, TStringSet2 const&, TId const id1, TPos const pos1, TId const id2, TPos const pos2, TPos const segLen, TTraceValue const tv);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(170)
template <typename TFragment, typename TStringSet, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(String<TFragment>& matches, TStringSet const&, TId const id1, TPos const pos1, TId const id2, TPos const pos2, TPos const seqLen, TTraceValue const tv);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(196)
template <typename TVertexDescriptor, typename TSpec, typename TStringSet, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(String<String<TVertexDescriptor, TSpec> >& nodeString, TStringSet const& str, TId const, TPos const pos1, TId const, TPos const pos2, TPos const segLen, TTraceValue const tv);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_base.h"(216)

//____________________________________________________________________________
// _configValueBottom

template <bool TTop, bool TLeft, bool TRight, typename TSpec> inline bool _configValueBottom(AlignConfig<TTop, TLeft, TRight, true, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(465)
template <bool TTop, bool TLeft, bool TRight, typename TSpec> inline bool _configValueBottom(AlignConfig<TTop, TLeft, TRight, false, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(472)

//____________________________________________________________________________
// _configValueLeft

template <bool TTop, bool TRight, bool TBottom, typename TSpec> inline bool _configValueLeft(AlignConfig<TTop, true, TRight, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(433)
template <bool TTop, bool TRight, bool TBottom, typename TSpec> inline bool _configValueLeft(AlignConfig<TTop, false, TRight, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(440)

//____________________________________________________________________________
// _configValueRight

template <bool TTop, bool TLeft, bool TBottom, typename TSpec> inline bool _configValueRight(AlignConfig<TTop, TLeft, true, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(449)
template <bool TTop, bool TLeft, bool TBottom, typename TSpec> inline bool _configValueRight(AlignConfig<TTop, TLeft, false, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(456)

//____________________________________________________________________________
// _configValueTop

template <bool TLeft, bool TRight, bool TBottom, typename TSpec> inline bool _configValueTop(AlignConfig<true, TLeft, TRight, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(417)
template <bool TLeft, bool TRight, bool TBottom, typename TSpec> inline bool _configValueTop(AlignConfig<false, TLeft, TRight, TBottom, TSpec> const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(424)

//____________________________________________________________________________
// _finishAlign

template <typename TString, typename TPos> inline void _finishAlign(Graph<Alignment<StringSet<TString, Dependent<> > > >&, TPos, TPos, TPos, TPos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(63)
template <typename T, typename TPos> inline void _finishAlign(T &, TPos, TPos, TPos, TPos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(76)

//____________________________________________________________________________
// _globalAlignment

template <typename TAlign, typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_gotoh.h"(304)
template <typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_gotoh.h"(333)
template <typename TAlign, typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, String<Pair<typename Value<TScore>::Type,int> > &maxCols, unsigned minColNum, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(403)
template <typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, String<Pair<typename Value<TScore>::Type,int> > &maxCols, unsigned minColNum, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(434)
template <typename TAlign, typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(461)
template <typename TStringSet, typename TScore, typename TAlignConfig, typename TDiagonal> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_needleman_wunsch.h"(490)
template <typename TAlign, typename TStringSet, typename TScore, typename TAlignConfig> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, TAlignConfig const, Gotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_gotoh.h"(290)
template <typename TStringSet, typename TScore, typename TAlignConfig> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, TAlignConfig const, Gotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_gotoh.h"(317)
template <typename TAlign, typename TStringSet, typename TScore, typename TSpec> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, AlignConfig<false, false, false, false, TSpec> const, Hirschberg);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_hirschberg.h"(497)
template <typename TStringSet, typename TScore, typename TSpec> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, AlignConfig<false, false, false, false, TSpec> const, Hirschberg);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_hirschberg.h"(520)
template <typename TAlign, typename TStringSet, typename TScore, typename TAlignConfig> inline typename Value<TScore>::Type _globalAlignment(TAlign& align, TStringSet const& str, TScore const& sc, TAlignConfig const, NeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_needleman_wunsch.h"(248)
template <typename TStringSet, typename TScore, typename TAlignConfig> inline typename Value<TScore>::Type _globalAlignment(TStringSet const& str, TScore const& sc, TAlignConfig const, NeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_needleman_wunsch.h"(273)

//____________________________________________________________________________
// _initAlign

template <typename TString> inline void _initAlign(Graph<Alignment<StringSet<TString, Dependent<> > > >& align, StringSet<TString, Dependent<> > const& str);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(44)
template <typename T, typename TString> inline void _initAlign(T & , StringSet<TString, Dependent<> > const& );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(52)

//____________________________________________________________________________
// _initFirstColumn

template <bool TTop, bool TRight, bool TBottom, typename TSpec, typename TElement, typename TCost> inline void _initFirstColumn(AlignConfig<TTop, false, TRight, TBottom, TSpec> const, TElement& element, TCost const cost);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(178)
template <bool TTop, bool TRight, bool TBottom, typename TSpec, typename TElement, typename TCost> inline void _initFirstColumn(AlignConfig<TTop, true, TRight, TBottom, TSpec> const, TElement& element, TCost const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(190)

//____________________________________________________________________________
// _initFirstRow

template <bool TLeft, bool TRight, bool TBottom, typename TSpec, typename TElement, typename TCost> inline void _initFirstRow(AlignConfig<false, TLeft, TRight, TBottom, TSpec> const, TElement& element, TCost const cost);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(202)
template <bool TLeft, bool TRight, bool TBottom, typename TSpec, typename TElement, typename TCost> inline void _initFirstRow(AlignConfig<true, TLeft, TRight, TBottom, TSpec> const, TElement& element, TCost const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(214)

//____________________________________________________________________________
// _isClumping

template <typename TSpec, typename TSize> inline bool _isClumping(String<bool, TSpec> const& forbidden, TSize row, TSize col, TSize len2);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(76)
template <typename TSize> inline bool _isClumping(Nothing&, TSize, TSize, TSize);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(89)

//____________________________________________________________________________
// _lastColumn

template <bool TTop, bool TLeft, bool TBottom, typename TSpec, typename TValue1, typename TIndex1, typename TColumn> inline void _lastColumn(AlignConfig<TTop, TLeft, false, TBottom, TSpec> const, TValue1& maxValue, TIndex1&, TColumn const& column);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(261)
template <bool TTop, bool TLeft, bool TBottom, typename TSpec, typename TValue1, typename TIndex1, typename TColumn> inline void _lastColumn(AlignConfig<TTop, TLeft, true, TBottom, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TColumn const& column);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(274)
template <bool TTop, bool TLeft, bool TBottom, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastColumn(AlignConfig<TTop, TLeft, false, TBottom, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TValue2 const val, TIndex2 const row, TIndex2 const col);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(361)
template <bool TTop, bool TLeft, bool TBottom, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastColumn(AlignConfig<TTop, TLeft, true, TBottom, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TValue2 const val, TIndex2 const row, TIndex2 const col);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(376)

//____________________________________________________________________________
// _lastRow

template <bool TTop, bool TLeft, bool TRight, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastRow(AlignConfig<TTop, TLeft, TRight, false, TSpec> const, TValue1&, TIndex1&, TValue2 const, TIndex2 const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(231)
template <bool TTop, bool TLeft, bool TRight, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastRow(AlignConfig<TTop, TLeft, TRight, true, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TValue2 const val, TIndex2 const index);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(245)
template <bool TTop, bool TLeft, bool TRight, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastRow(AlignConfig<TTop, TLeft, TRight, false, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TValue2 const val, TIndex2 const row, TIndex2 const col);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(391)
template <bool TTop, bool TLeft, bool TRight, typename TSpec, typename TValue1, typename TIndex1, typename TValue2, typename TIndex2> inline void _lastRow(AlignConfig<TTop, TLeft, TRight, true, TSpec> const, TValue1& maxValue, TIndex1& maxIndex, TValue2 const val, TIndex2 const row, TIndex2 const col);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(406)

//____________________________________________________________________________
// _localAlignment

template <typename TAlign, typename TStringSet, typename TForbidden, typename TScore, typename TDiagonal> inline typename Value<TScore>::Type _localAlignment(TStringSet& str, TAlign& align, TForbidden& forbidden, TScore const& sc, TDiagonal diag1, TDiagonal diag2, BandedSmithWatermanClump);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(305)
template <typename TString, typename TAlignments, typename TScores, typename TScoreValue, typename TSpec2, typename TDiagonal> inline void _localAlignment(StringSet<TString, Dependent<> > const& str, TAlignments& alignments, TScores& scores, Score<TScoreValue, TSpec2> const& sc, TScoreValue minScore, TDiagonal diag1, TDiagonal diag2, BandedSmithWatermanClump);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_banded_smith_waterman_clump.h"(335)
template <typename TAlign, typename TStringSet, typename TScore> inline typename Value<TScore>::Type _localAlignment(TAlign& align, TStringSet const& str, TScore const& sc, SmithWaterman);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(347)
template <typename TStringSet, typename TScore> inline typename Value<TScore>::Type _localAlignment(TStringSet const& str, TScore const& sc, SmithWaterman);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(375)
template <typename TAlign, typename TStringSet, typename TForbidden, typename TScore> inline typename Value<TScore>::Type _localAlignment(TAlign& align, TStringSet& str, TForbidden& forbidden, TScore const& sc, SmithWatermanClump);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman_clump.h"(53)
template <typename TString, typename TMatches, typename TScores, typename TScore, typename TSize1> inline void _localAlignment(StringSet<TString, Dependent<> > const& str, TMatches& matches, TScores& scores, TScore const& sc, TSize1 numAlignments, SmithWatermanClump);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman_clump.h"(94)

//____________________________________________________________________________
// _maxOfAlignment

template <typename TScoreValue, bool TTop, bool TLeft, typename TSpec, typename TValue, typename TIndex, typename TSize> inline TScoreValue _maxOfAlignment(AlignConfig<TTop, TLeft, false, false, TSpec> const, TValue& maxValue, TIndex&, TSize const, TSize const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(299)
template <typename TScoreValue, bool TTop, bool TLeft, typename TSpec, typename TValue, typename TIndex, typename TSize> inline TScoreValue _maxOfAlignment(AlignConfig<TTop, TLeft, true, false, TSpec> const, TValue& maxValue, TIndex& maxIndex, TSize const len1, TSize const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(313)
template <typename TScoreValue, bool TTop, bool TLeft, typename TSpec, typename TValue, typename TIndex, typename TSize> inline TScoreValue _maxOfAlignment(AlignConfig<TTop, TLeft, false, true, TSpec> const, TValue& maxValue, TIndex& maxIndex, TSize const, TSize const len2);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(328)
template <typename TScoreValue, bool TTop, bool TLeft, typename TSpec, typename TValue, typename TIndex, typename TSize> inline TScoreValue _maxOfAlignment(AlignConfig<TTop, TLeft, true, true, TSpec> const, TValue& maxValue, TIndex& maxIndex, TSize const len1, TSize const len2);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(343)

//____________________________________________________________________________
// _pairWiseSumOfPairsScore

template <typename TStringSet, typename TCargo, typename TSpec, typename TScore, typename TAlignConfig> inline typename Value<TScore>::Type _pairWiseSumOfPairsScore(Graph<Alignment<TStringSet, TCargo, TSpec> > const& g, TScore const& sc, TAlignConfig const);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_config.h"(484)

//____________________________________________________________________________
// _setForbiddenCell

template <typename TSpec, typename TSize> inline void _setForbiddenCell(String<bool, TSpec>& forbidden, TSize len1, TSize len2, TSize numRows);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(53)
template <typename TSize> inline void _setForbiddenCell(Nothing&, TSize, TSize, TSize);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_smith_waterman.h"(65)

//____________________________________________________________________________
// globalAlignment

template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TTag> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(81)
template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TTag> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(95)
template <typename TStringSet, typename TScoreValue, typename TSpec, typename TTag> inline TScoreValue globalAlignment(TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(107)
template <typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TTag> inline TScoreValue globalAlignment(TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(120)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TTag> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(132)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TAlignConfig, typename TTag> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TAlignConfig const, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(146)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(162)
template <typename TString, typename TAlignSpec, typename TStringSet, typename TScoreValue, typename TScoreSpec, typename TDiagonal> inline TScoreValue globalAlignment(Align<TString, TAlignSpec> & align, TStringSet const & stringSet, Score<TScoreValue, TScoreSpec> const & sc, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(178)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TDiagonal> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(196)
template <typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(211)
template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TDiagonal> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(227)
template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedNeedlemanWunsch);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(243)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(259)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TDiagonal> inline TScoreValue globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(274)
template <typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(289)
template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TDiagonal> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(305)
template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TAlignConfig, typename TDiagonal> inline TScoreValue globalAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TAlignConfig const, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(321)
template <typename TString, typename TAlignSpec, typename TStringSet, typename TScoreValue, typename TScoreSpec, typename TDiagonal> inline TScoreValue globalAlignment(Align<TString, TAlignSpec> & align, TStringSet const & stringSet, Score<TScoreValue, TScoreSpec> const & sc, TDiagonal diag1, TDiagonal diag2, BandedGotoh);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(335)
template <typename TStringSet, typename TCargo, typename TSpec> inline int globalAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Lcs);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(350)

//____________________________________________________________________________
// localAlignment

template <typename TAlign, typename TStringSet, typename TScoreValue, typename TSpec, typename TTag> inline TScoreValue localAlignment(TAlign& file, TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(384)
template <typename TStringSet, typename TScoreValue, typename TSpec, typename TTag> inline TScoreValue localAlignment(TStringSet const& str, Score<TScoreValue, TSpec> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(395)
template <typename TStringSet, typename TCargo, typename TSpec, typename TScoreValue, typename TSpec2, typename TTag> inline TScoreValue localAlignment(Graph<Alignment<TStringSet, TCargo, TSpec> >& g, Score<TScoreValue, TSpec2> const& sc, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(407)

//____________________________________________________________________________
// multiLocalAlignment

template <typename TString, typename TMatches, typename TScores, typename TScoreValue, typename TSpec2, typename TSize, typename TTag> inline void multiLocalAlignment(StringSet<TString, Dependent<> > const& str, TMatches& matches, TScores& scores, Score<TScoreValue, TSpec2> const& sc, TSize numAlignments, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(450)
template <typename TString, typename TAlignments, typename TScores, typename TScoreValue, typename TSpec2, typename TDiagonal, typename TTag> inline void multiLocalAlignment(StringSet<TString, Dependent<> > const& str, TAlignments& alignments, TScores& scores, Score<TScoreValue, TSpec2> const& sc, TScoreValue minScore, TDiagonal diag1, TDiagonal diag2, TTag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/graph_align/graph_align_interface.h"(464)

} //namespace SEQAN_NAMESPACE_MAIN

#endif

