// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_SEQUENCE_JOURNALED_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_SEQUENCE_JOURNALED_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Cargo

template <typename T> struct Cargo;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_node.h"(79)

//____________________________________________________________________________
// InsertionBuffer

template <typename T> struct InsertionBuffer;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(192)

//____________________________________________________________________________
// JournalEntries

template <typename TNode, typename TTreeSpec> class JournalEntries;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(51)
template <typename TNode, typename TTreeSpec> class JournalEntries;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(61)

//____________________________________________________________________________
// JournalEntriesIterSpec

template <typename TJournalEntriesSpec> struct JournalEntriesIterSpec;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(47)
template <typename TJournalEntriesSpec> struct JournalEntriesIterSpec;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_forwards.h"(47)

//____________________________________________________________________________
// JournalEntriesUnorderedTreeNode

template <typename TCargo> struct JournalEntriesUnorderedTreeNode;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_node.h"(53)

//____________________________________________________________________________
// JournalEntry

template <typename TPos_, typename TSize_> struct JournalEntry;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entry.h"(55)

//____________________________________________________________________________
// JournalEntryLtByVirtualPos

template <typename TPos, typename TSize> struct JournalEntryLtByVirtualPos;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entry.h"(94)

//____________________________________________________________________________
// JournalType

template <typename T> struct JournalType;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(307)

//____________________________________________________________________________
// Journaled

template <typename THostSpec, typename TJournalSpec , typename TBufferSpec > struct Journaled;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(65)

//____________________________________________________________________________
// JournaledStringIterSpec

template <typename TJournaledStringSpec> struct JournaledStringIterSpec;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(47)

//____________________________________________________________________________
// SortedArray

struct SortedArray;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(47)
struct SortedArray;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_forwards.h"(44)

//____________________________________________________________________________
// UnbalancedTree

struct UnbalancedTree;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(57)
struct UnbalancedTree;       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_forwards.h"(42)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// _addToVirtualPositionsRightOf

template <typename TNode> inline void _addToVirtualPositionsRightOf(TNode * node, typename Position<TNode>::Type const & pos, typename Position<TNode>::Type const & delta);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(288)

//____________________________________________________________________________
// _checkSortedArrayTree

template <typename TCargo> bool _checkSortedArrayTree(JournalEntries<TCargo, SortedArray> const & tree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(128)

//____________________________________________________________________________
// _copyJournalEntriesNodes

template <typename TNode, typename TAllocator> void _copyJournalEntriesNodes(TNode * & target, TAllocator & allocator, TNode * const & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(120)

//____________________________________________________________________________
// _initJournalEntriesIterator

template <typename TJournalEntries> inline void _initJournalEntriesIterator(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator, TJournalEntries & tree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(193)

//____________________________________________________________________________
// _initJournalEntriesIteratorEnd

template <typename TJournalEntries> inline void _initJournalEntriesIteratorEnd(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator, TJournalEntries & tree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(211)

//____________________________________________________________________________
// _initJournaledStringIterator

template <typename TJournaledString, typename TJournalSpec> inline void _initJournaledStringIterator(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator, TJournaledString & journalString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(218)

//____________________________________________________________________________
// _initJournaledStringIteratorEnd

template <typename TJournaledString, typename TJournalSpec> inline void _initJournaledStringIteratorEnd(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator, TJournaledString & journalString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(231)

//____________________________________________________________________________
// _setLength

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline void _setLength(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, size_t newLength);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(769)

//____________________________________________________________________________
// _subtractFromVirtualPositionsRightOf

template <typename TNode> inline void _subtractFromVirtualPositionsRightOf(TNode * node, typename Position<TNode>::Type const & pos, typename Position<TNode>::Type const & delta);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(264)

//____________________________________________________________________________
// _updateSegmentIterators

template <typename TJournaledString, typename TJournalSpec> inline void _updateSegmentIterators(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(241)

//____________________________________________________________________________
// assign

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TSource> inline void assign(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & target, TSource const & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(366)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TSource> inline void assign(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & target, TSource & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(377)

//____________________________________________________________________________
// assignInfix

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TBeginPos, typename TEndPos, typename TSequence2> inline void assignInfix(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TBeginPos beginPos, TEndPos endPos, TSequence2 const & valueString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(579)

//____________________________________________________________________________
// assignValue

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos, typename TValue2> inline void assignValue(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TPos pos, TValue2 const & value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(594)
template <typename TJournaledString, typename TJournalSpec, typename TValue> inline void assignValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & me, TValue const & _value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(289)
template <typename TJournaledString, typename TJournalSpec, typename TValue> inline void assignValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & iterator, TValue const & _value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(299)

//____________________________________________________________________________
// atEnd

template <typename TJournalEntries> inline bool atEnd(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(347)
template <typename TJournalEntries> inline bool atEnd(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(356)

//____________________________________________________________________________
// begin

template <typename TCargo> typename Iterator<JournalEntries<TCargo, SortedArray>, Standard>::Type begin(JournalEntries<TCargo, SortedArray> & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(151)
template <typename TCargo> typename Iterator<JournalEntries<TCargo, SortedArray> const, Standard>::Type begin(JournalEntries<TCargo, SortedArray> const & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(160)
template <typename TNode> inline typename Iterator<JournalEntries<TNode, UnbalancedTree> const, Standard>::Type begin(JournalEntries<TNode, UnbalancedTree> const & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(146)
template <typename TNode> inline typename Iterator<JournalEntries<TNode, UnbalancedTree>, Standard>::Type begin(JournalEntries<TNode, UnbalancedTree> & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(155)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Iterator<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const, Standard>::Type begin(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journalString, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(167)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Iterator<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> >, Standard>::Type begin(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journalString, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(179)

//____________________________________________________________________________
// cargo

template <typename TCargo> typename Cargo<JournalEntriesUnorderedTreeNode<TCargo> >::Type & cargo(JournalEntriesUnorderedTreeNode<TCargo> & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_node.h"(119)

//____________________________________________________________________________
// checkOrder

template <typename TNode> inline bool checkOrder(TNode * const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(183)

//____________________________________________________________________________
// checkOrderRec

template <typename TNode> inline bool checkOrderRec(TNode * const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(166)

//____________________________________________________________________________
// checkStructure

template <typename TNode> inline bool checkStructure(TNode * const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(210)

//____________________________________________________________________________
// checkStructureRec

template <typename TNode> inline bool checkStructureRec(TNode * const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(193)

//____________________________________________________________________________
// checkVirtualPositions

template <typename TNode> inline bool checkVirtualPositions(TNode * const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(157)

//____________________________________________________________________________
// checkVirtualPositionsRec

template <typename TNode> inline bool checkVirtualPositionsRec(TNode * const & node, unsigned & virtualPosition);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(139)

//____________________________________________________________________________
// clear

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline void clear(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(483)

//____________________________________________________________________________
// end

template <typename TCargo> typename Iterator<JournalEntries<TCargo, SortedArray>, Standard>::Type end(JournalEntries<TCargo, SortedArray> & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(169)
template <typename TCargo> typename Iterator<JournalEntries<TCargo, SortedArray> const, Standard>::Type end(JournalEntries<TCargo, SortedArray> const & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(178)
template <typename TNode> inline typename Iterator<JournalEntries<TNode, UnbalancedTree> const, Standard>::Type end(JournalEntries<TNode, UnbalancedTree> const & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(164)
template <typename TNode> inline typename Iterator<JournalEntries<TNode, UnbalancedTree>, Standard>::Type end(JournalEntries<TNode, UnbalancedTree> & journalTree, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(177)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Iterator<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const, Standard>::Type end(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journalString, Standard);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(191)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Iterator<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> >, Standard>::Type end(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journalString, Standard const &);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(203)

//____________________________________________________________________________
// erase

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TBeginPos, typename TEndPos> inline void erase(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TBeginPos pos, TEndPos posEnd);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(514)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos> inline void erase(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(529)

//____________________________________________________________________________
// findInJournalEntries

template <typename TCargo, typename TPos> inline typename Iterator<JournalEntries<TCargo, SortedArray> const, Standard>::Type findInJournalEntries(JournalEntries<TCargo, SortedArray> const & journalEntries, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(201)
template <typename TCargo> inline typename Iterator<JournalEntries<TCargo, UnbalancedTree> const, Standard>::Type findInJournalEntries(JournalEntries<TCargo, UnbalancedTree> const & journalEntries, typename Position<TCargo>::Type const & pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(308)

//____________________________________________________________________________
// findJournalEntry

template <typename TCargo, typename TPos> inline TCargo const & findJournalEntry(JournalEntries<TCargo, SortedArray> const & journalEntries, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(228)
template <typename TCargo> inline TCargo const & findJournalEntry(JournalEntries<TCargo, UnbalancedTree> const & journalEntries, typename Position<TCargo>::Type const & pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(340)

//____________________________________________________________________________
// getObjectId

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline const void * getObjectId(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(858)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline const void * getObjectId(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(867)

//____________________________________________________________________________
// getValue

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename GetValue<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const>::Type getValue(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString, typename Position<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(712)
template <typename TJournaledString, typename TJournalSpec> inline typename GetValue<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type getValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(401)
template <typename TJournaledString, typename TJournalSpec> inline typename GetValue<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type getValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(415)

//____________________________________________________________________________
// goLeft

template <typename TJournalEntries> inline bool goLeft(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(285)

//____________________________________________________________________________
// goRight

template <typename TJournalEntries> inline bool goRight(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(307)

//____________________________________________________________________________
// goUp

template <typename TJournalEntries> inline bool goUp(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(329)

//____________________________________________________________________________
// hasLeftChild

template <typename TJournalEntries> inline bool hasLeftChild(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(276)

//____________________________________________________________________________
// hasParent

template <typename TJournalEntries> inline bool hasParent(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(320)

//____________________________________________________________________________
// hasRightChild

template <typename TJournalEntries> inline bool hasRightChild(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(298)

//____________________________________________________________________________
// host

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Host<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type & host(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(456)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Host<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type const & host(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(465)

//____________________________________________________________________________
// insert

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TString, typename TPos> inline void insert(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TPos pos, TString const & seq);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(544)

//____________________________________________________________________________
// insertValue

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos, typename TValue2> inline void insertValue(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TPos pos, TValue2 const & value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(561)

//____________________________________________________________________________
// isFlat

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline bool isFlat(String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(875)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline bool isFlat(String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(895)

//____________________________________________________________________________
// isGapInHost

template <typename TNode, typename TJournalSpec, typename TPos> inline bool isGapInHost(JournalEntries<TNode, TJournalSpec> const & journalEntries, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(485)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos> inline bool isGapInHost(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(754)

//____________________________________________________________________________
// journalTreeToDot

template <typename TStream, typename TNode> void journalTreeToDot(TStream & stream, unsigned & nextId, JournalEntries<TNode, UnbalancedTree> const & journalTree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(687)

//____________________________________________________________________________
// journalTreeToDotRec

template <typename TStream, typename TNode> void journalTreeToDotRec(TStream & stream, unsigned & nextId, TNode const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(668)

//____________________________________________________________________________
// length

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline typename Size<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type length(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(656)

//____________________________________________________________________________
// moveValue

template <typename TJournaledString, typename TJournalSpec, typename TValue> inline void moveValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & me, TValue const & _value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(312)
template <typename TJournaledString, typename TJournalSpec, typename TValue> inline void moveValue(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & me, TValue const & _value);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(322)

//____________________________________________________________________________
// operator!=

template <typename TJournalEntries> inline bool operator!=(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & a, Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(511)
template <typename TJournalEntries> inline bool operator!=(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & a, typename IterComplementConst<Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(521)
template <typename TJournaledString, typename TJournalSpec> inline bool operator!=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(661)
template <typename TJournaledString, typename TJournalSpec> inline bool operator!=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(671)

//____________________________________________________________________________
// operator*

template <typename TJournaledString, typename TJournalSpec> inline typename Reference<TJournaledString>::Type operator*(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(467)
template <typename TJournaledString, typename TJournalSpec> inline typename Reference<TJournaledString>::Type operator*(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(476)

//____________________________________________________________________________
// operator+

template <typename TJournaledString, typename TJournalSpec> inline Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > operator+(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & iterator, typename Size<TJournaledString>::Type const & len);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(542)

//____________________________________________________________________________
// operator++

template <typename TJournalEntries> inline Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & operator++(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(366)
template <typename TJournalEntries> inline Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > operator++(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator, int );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(412)
template <typename TJournaledString, typename TJournalSpec> inline Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & operator++(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(429)
template <typename TJournaledString, typename TJournalSpec> inline Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > operator++(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator, int );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(456)

//____________________________________________________________________________
// operator+=

template <typename TJournaledString, typename TJournalSpec, typename TLen> inline Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & operator+=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & iterator, TLen len_);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(486)

//____________________________________________________________________________
// operator-

template <typename TJournaledString, typename TJournalSpec> inline typename Difference<TJournaledString>::Type operator-(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & it1, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & it2);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(554)

//____________________________________________________________________________
// operator--

template <typename TJournalEntries> inline Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & operator--(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(423)
template <typename TJournalEntries> inline Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > operator--(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator, int );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(479)

//____________________________________________________________________________
// operator<

template <typename TJournaledString, typename TJournalSpec> inline bool operator<(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(681)
template <typename TJournaledString, typename TJournalSpec> inline bool operator<(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(691)

//____________________________________________________________________________
// operator<<

template <typename TStream, typename TNode> inline TStream & operator<<(TStream & stream, JournalEntries<TNode, SortedArray> const & tree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(116)
template <typename TStream, typename TNode> inline TStream & operator<<(TStream & stream, JournalEntries<TNode, UnbalancedTree> const & tree);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(234)
template <typename TStream, typename TCargo> TStream & operator<<(TStream & stream, JournalEntriesUnorderedTreeNode<TCargo> const & node);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_node.h"(99)
template <typename TStream, typename TPos, typename TSize> TStream & operator<<(TStream & stream, JournalEntry<TPos, TSize> const & entry);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entry.h"(133)
template <typename TStream, typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline TStream & operator<<(TStream & stream, String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & s);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(337)

//____________________________________________________________________________
// operator<=

template <typename TJournaledString, typename TJournalSpec> inline bool operator<=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(701)
template <typename TJournaledString, typename TJournalSpec> inline bool operator<=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(711)

//____________________________________________________________________________
// operator==

template <typename TJournalEntries> inline bool operator==(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & a, Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(491)
template <typename TJournalEntries> inline bool operator==(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & a, typename IterComplementConst<Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(501)
template <typename TJournaledString, typename TJournalSpec> inline bool operator==(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(628)
template <typename TJournaledString, typename TJournalSpec> inline bool operator==(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(650)

//____________________________________________________________________________
// operator>

template <typename TJournaledString, typename TJournalSpec> inline bool operator>(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(721)
template <typename TJournaledString, typename TJournalSpec> inline bool operator>(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(731)

//____________________________________________________________________________
// operator>=

template <typename TJournaledString, typename TJournalSpec> inline bool operator>=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(741)
template <typename TJournaledString, typename TJournalSpec> inline bool operator>=(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & a, typename IterComplementConst<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type const & b);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(751)

//____________________________________________________________________________
// position

template <typename TJournaledString, typename TJournalSpec> inline typename Position<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const>::Type position(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(367)

//____________________________________________________________________________
// recordErase

template <typename TCargo> inline void recordErase(JournalEntries<TCargo, SortedArray> & tree, typename Position<TCargo>::Type pos, typename Position<TCargo>::Type posEnd);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(309)
template <typename TCargo> inline void recordErase(JournalEntries<TCargo, UnbalancedTree> & tree, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & pos, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & posEnd);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(351)

//____________________________________________________________________________
// recordInsertion

template <typename TCargo> inline void recordInsertion(JournalEntries<TCargo, SortedArray> & tree, typename Position<TCargo>::Type virtualPosition, typename Position<TCargo>::Type physicalBeginPos, typename Size<TCargo>::Type len);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(239)
template <typename TCargo> inline void recordInsertion(JournalEntries<TCargo, UnbalancedTree> & tree, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & virtualPos, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & physicalBeginPos, typename Size<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & length);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(538)

//____________________________________________________________________________
// reinit

template <typename TCargo> inline void reinit(JournalEntries<TCargo, SortedArray> & tree, typename Size<TCargo>::Type originalStringLength);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(188)
template <typename TCargo> inline void reinit(JournalEntries<TCargo, UnbalancedTree> & tree, typename Size<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type originalStringLength);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree.h"(245)

//____________________________________________________________________________
// replace

template <typename TTargetValue, typename TTargetHostSpec, typename TTargetJournalSpec, typename TTargetBufferSpec, typename TPositionBegin, typename TPositionEnd, typename TSource, typename TExpand> inline void replace(String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > & target, TPositionBegin posBegin, TPositionEnd posEnd, TSource const & source, Tag<TExpand> const & );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(785)
template <typename TTargetValue, typename TTargetHostSpec, typename TTargetJournalSpec, typename TTargetBufferSpec, typename TPositionBegin, typename TPositionEnd, typename TSource, typename TExpand> inline void replace(String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > & target, TPositionBegin posBegin, TPositionEnd posEnd, TSource const & source, typename Size<String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > >::Type limit, Tag<TExpand> const & tag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(798)
template <typename TTargetValue, typename TTargetHostSpec, typename TTargetJournalSpec, typename TTargetBufferSpec, typename TPositionBegin, typename TPositionEnd, typename TSourceValue, typename TExpand> inline void replace(String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > & target, TPositionBegin posBegin, TPositionEnd posEnd, TSourceValue const * source, Tag<TExpand> const & );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(821)
template <typename TTargetValue, typename TTargetHostSpec, typename TTargetJournalSpec, typename TTargetBufferSpec, typename TPositionBegin, typename TPositionEnd, typename TSourceValue, typename TExpand> inline void replace(String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > & target, TPositionBegin posBegin, TPositionEnd posEnd, TSourceValue const * source, typename Size<String<TTargetValue, Journaled<TTargetHostSpec, TTargetJournalSpec, TTargetBufferSpec> > >::Type limit, Tag<TExpand> const & tag);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(835)

//____________________________________________________________________________
// set

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline void set(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & target, String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(393)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec> inline void set(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & target, String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(406)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TSource> inline void set(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & target, TSource const & source);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(417)

//____________________________________________________________________________
// setHost

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TSequence2> inline void setHost(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & journaledString, TSequence2 & str);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(436)

//____________________________________________________________________________
// setPosition

template <typename TJournaledString, typename TJournalSpec, typename TPosition> inline void setPosition(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & , TPosition );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(390)

//____________________________________________________________________________
// value

template <typename TJournalEntries> inline typename Value<Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > >::Type value(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(234)
template <typename TJournalEntries> inline typename Value<Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > >::Type value(Iter<TJournalEntries, JournalEntriesIterSpec<UnbalancedTree> > const & iterator);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_unbalanced_tree_iterator.h"(243)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos> inline typename Reference<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type value(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > & me, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(676)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos> inline typename Reference<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const>::Type value(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & me, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(687)
template <typename TJournaledString, typename TJournalSpec> inline typename Reference<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > >::Type value(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > & me);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(266)
template <typename TJournaledString, typename TJournalSpec> inline typename Reference<Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const>::Type value(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & me);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(276)

//____________________________________________________________________________
// valueConstruct

template <typename TJournaledString, typename TJournalSpec> inline void valueConstruct(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(333)
template <typename TJournaledString, typename TJournalSpec, typename TParam> inline void valueConstruct(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & it, TParam const & param_);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(341)
template <typename TJournaledString, typename TJournalSpec, typename TParam> inline void valueConstruct(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & it, TParam & param_, Move const & );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(350)

//____________________________________________________________________________
// valueDestruct

template <typename TJournaledString, typename TJournalSpec> inline void valueDestruct(Iter<TJournaledString, JournaledStringIterSpec<TJournalSpec> > const & );       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled_iterator.h"(359)

//____________________________________________________________________________
// virtualToHostPosition

template <typename TNode, typename TJournalSpec, typename TPos> inline typename Position<typename Cargo<TNode>::Type >::Type virtualToHostPosition(JournalEntries<TNode, TJournalSpec> const & journalEntries, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/journal_entries_sorted_array.h"(444)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBufferSpec, typename TPos> inline typename Position<String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > >::Type virtualToHostPosition(String<TValue, Journaled<THostSpec, TJournalSpec, TBufferSpec> > const & journaledString, TPos pos);       	// "/Users/fabianbuske/Documents/research/triplex/seqan/core/include/seqan/sequence_journaled/sequence_journaled.h"(739)

} //namespace seqan

#endif

