name: compile and test clang
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'include/**'
      - 'makefiles/Makefile.clang'
      - '.github/workflows/compile-and-test-clang.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'include/**'
      - 'makefiles/Makefile.clang'
      - '.github/workflows/compile-and-test-clang.yml'
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up clang
        run: >
          sudo apt-get update -y &&
          sudo apt-get install -y build-essential clang libomp-dev
      - name: compile pato
        run: >
          make clang BUILD=serial -j4 &&
          make clang BUILD=release -j4
        working-directory: ${{ github.workspace }}
      - name: run tests
        run: bash test/test.bash clang
        working-directory: ${{ github.workspace }}
  macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up clang
        run: brew install llvm@15 libomp
      - name: compile pato
        run: >
          CXXFLAGS="-I$(brew --prefix libomp)/include $($(brew --prefix llvm@15)/bin/llvm-config --cxxflags)" LDFLAGS="-L$(brew --prefix libomp)/lib $($(brew --prefix llvm@15)/bin/llvm-config --ldflags)" make clang -j4 BUILD=release \
            CXX=$(brew --prefix llvm@15)/bin/clang++ \
            LD=$(brew --prefix llvm@15)/bin/clang++ &&
          CXXFLAGS="-I$(brew --prefix libomp)/include $($(brew --prefix llvm@15)/bin/llvm-config --cxxflags)" LDFLAGS="-L$(brew --prefix libomp)/lib $($(brew --prefix llvm@15)/bin/llvm-config --ldflags)" make clang -j4 BUILD=serial \
            CXX=$(brew --prefix llvm@15)/bin/clang++ \
            LD=$(brew --prefix llvm@15)/bin/clang++
        working-directory: ${{ github.workspace }}
      - name: run tests
        run: bash test/test.bash clang
        working-directory: ${{ github.workspace }}
