name: compile and test gnu
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: set up gcc
          run: >
            sudo apt-get update -y &&
            sudo apt-get install -y build-essential &&
            sudo apt-get install -y libomp-dev
        - name: compile pato
          run: make BUILD=serial LDLIBS="-lrt" -j 4 && make BUILD=release LDLIBS="-lrt" -j 4
          working-directory: ${{ github.workspace }}
        - name: run tests
          run: bash test.sh
          working-directory: ${{ github.workspace }}/test
